/* created at 2018/4/10 by BlueSky @cilicili */
/*const API_SERVER_HOSTNAME = '127.0.0.1';
const API_SERVER_PORT = 9011;
const API_SERVER = `//${API_SERVER_HOSTNAME}:${API_SERVER_PORT}`;
const UPLOAD_SERVER_HOSTNAME = '127.0.0.1';
const UPLOAD_SERVER_PORT = 9002;
const UPLOAD_SERVER = `//${UPLOAD_SERVER_HOSTNAME}:${UPLOAD_SERVER_PORT}`;
const STORAGE_SERVER_HOSTNAME = '127.0.0.1';
const STORAGE_SERVER_PORT = 9003;
const STORAGE_SERVER = `//${STORAGE_SERVER_HOSTNAME}:${STORAGE_SERVER_PORT}`;*/

$.ajaxSetup({
    async: false
});

const API_SERVER_padEnd = SERVICE_PATH => `/api/${SERVICE_PATH}`;
